### ISSUE TITLE
[BUG] The plugin stay in a infinite waiting and seem not work after installation

### ISSUE THREAD

**Issue by p4535992** [ONLYOFFICE/plugin-drawio#4]
**Details:**
Onlyoffice Version: ONLYOFFICE Desktop Editors versione 7.0.1.37
OS: Windows 10

**Steps:**
- Download the project as zip
- Unzip
- enter the folder and zip all the file in a  zip file named plugin-drawio.zip
- rename the file "plugin-drawio.zip" to "plugin-drawio.plugin"
- Open desktop editor 
- Go to plugin tab
- Click on settings and then on add plugins
- Select the file ""plugin-drawio.plugin"
- Loaded with success , click on the plugin button
- [Here the bug] Waiting dialog infinite and after  a long time i can click on the insert button but is do nothing

Did i miss some step ? or configuration ?
Did i need to install draw.io on the machine or is enough the file .drawio ?

**Comment by p4535992** [comment]
i will check my network, there is a proxy in the middle...
here the plugin file i'm using:
[plugin-drawio-master.zip](https://github.com/ONLYOFFICE/plugin-drawio/files/8676700/plugin-drawio-master.zip)
this is the zip i rename "plugin-drawio-master.plugin"

**Comment by ShockwaveNN** [comment]
@p4535992 Yep, I've rechecked you plugin and it works fine for me too

I'm strongly think that's a network issue

**Comment by p4535992** [comment]
k ty for the support i will close the ticket.
